CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_companies_name UNIQUE (name),
    CONSTRAINT ck_companies_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NULL,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NULL,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    role VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    onboarding_status VARCHAR(40) NOT NULL,
    profile_photo_path VARCHAR(500) NULL,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_app_users_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT uk_app_users_normalized_email UNIQUE (normalized_email),
    CONSTRAINT ck_app_users_role CHECK (role IN ('SUPERADMIN', 'COMPANY_ADMIN', 'MOD_USER', 'USER')),
    CONSTRAINT ck_app_users_status CHECK (status IN ('PENDING', 'ACTIVE', 'DISABLED')),
    CONSTRAINT ck_app_users_onboarding_status CHECK (onboarding_status IN ('NOT_REQUIRED', 'INVITED', 'PASSWORD_SETUP_REQUIRED', 'COMPLETED')),
    CONSTRAINT ck_app_users_company_scope CHECK (
        (role = 'SUPERADMIN' AND company_id IS NULL)
        OR
        (role <> 'SUPERADMIN' AND company_id IS NOT NULL)
    )
);

CREATE INDEX idx_app_users_company_id ON app_users (company_id);
CREATE INDEX idx_app_users_role ON app_users (role);
CREATE INDEX idx_app_users_status ON app_users (status);

CREATE TABLE invite_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invite_tokens_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_invite_tokens_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_invite_tokens_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),
    CONSTRAINT uk_invite_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_invite_tokens_company_id ON invite_tokens (company_id);
CREATE INDEX idx_invite_tokens_user_id ON invite_tokens (user_id);
CREATE INDEX idx_invite_tokens_expires_at ON invite_tokens (expires_at);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);