CREATE TABLE stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NULL,
    content_type VARCHAR(120) NOT NULL,
    storage_path VARCHAR(700) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stored_files_owner_user
        FOREIGN KEY (owner_user_id)
        REFERENCES app_users (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_stored_files_owner_user_id
    ON stored_files (owner_user_id);

ALTER TABLE app_users
    ADD COLUMN profile_photo_file_id BIGINT NULL;

ALTER TABLE app_users
    ADD CONSTRAINT fk_app_users_profile_photo_file
        FOREIGN KEY (profile_photo_file_id)
        REFERENCES stored_files (id)
        ON DELETE SET NULL;

CREATE INDEX idx_app_users_profile_photo_file_id
    ON app_users (profile_photo_file_id);