CREATE TABLE auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(40) NOT NULL,
    company_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    created_by_user_id BIGINT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_auth_tokens_company
        FOREIGN KEY (company_id)
        REFERENCES companies (id),

    CONSTRAINT fk_auth_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES "user" (id),

    CONSTRAINT fk_auth_tokens_created_by_user
        FOREIGN KEY (created_by_user_id)
        REFERENCES "user" (id),

    CONSTRAINT uk_auth_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT ck_auth_tokens_type
        CHECK (type IN ('INVITE', 'PASSWORD_RESET')),

    CONSTRAINT ck_auth_tokens_scope
        CHECK (
            (
                type = 'INVITE'
                AND company_id IS NOT NULL
                AND created_by_user_id IS NOT NULL
            )
            OR
            (
                type = 'PASSWORD_RESET'
                AND company_id IS NULL
                AND created_by_user_id IS NULL
            )
        )
);

CREATE INDEX idx_auth_tokens_type_user_id
    ON auth_tokens (type, user_id);

CREATE INDEX idx_auth_tokens_type_company_id
    ON auth_tokens (type, company_id);

CREATE INDEX idx_auth_tokens_type_created_by_user_id
    ON auth_tokens (type, created_by_user_id);

CREATE INDEX idx_auth_tokens_active_expiry
    ON auth_tokens (type, expires_at)
    WHERE used_at IS NULL;