CREATE TABLE workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120) NOT NULL,
    description VARCHAR(1000) NULL,
    status VARCHAR(20) NOT NULL,
    revision BIGINT NOT NULL,
    definition_json JSONB NOT NULL,
    created_by_email VARCHAR(320) NOT NULL,
    updated_by_email VARCHAR(320) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_workflows_company
        FOREIGN KEY (company_id)
        REFERENCES companies (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_workflows_company_normalized_name
        UNIQUE (company_id, normalized_name),
    CONSTRAINT ck_workflows_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_workflows_revision
        CHECK (revision > 0),
    CONSTRAINT ck_workflows_name_trimmed
        CHECK (name = BTRIM(name) AND name <> ''),
    CONSTRAINT ck_workflows_normalized_name
        CHECK (normalized_name = LOWER(BTRIM(normalized_name)) AND normalized_name <> ''),
    CONSTRAINT ck_workflows_definition_object
        CHECK (JSONB_TYPEOF(definition_json) = 'object'),
    CONSTRAINT ck_workflows_definition_nodes
        CHECK (COALESCE(JSONB_TYPEOF(definition_json -> 'nodes'), '') = 'array'),
    CONSTRAINT ck_workflows_definition_edges
        CHECK (COALESCE(JSONB_TYPEOF(definition_json -> 'edges'), '') = 'array'),
    CONSTRAINT ck_workflows_definition_metadata
        CHECK (COALESCE(JSONB_TYPEOF(definition_json -> 'metadata'), '') = 'object')
);

CREATE INDEX idx_workflows_company_updated
    ON workflows (company_id, updated_at DESC, id DESC);

CREATE INDEX idx_workflows_company_status_updated
    ON workflows (company_id, status, updated_at DESC, id DESC);