import { createFormPluginDefinition } from "@/shared/plugins/form/create-form-plugin-definition";
import type { FlatFormSchema } from "@/shared/plugins/form/form-schema-types";
import { pluginMessages } from "@/shared/plugins/messages/plugin-messages";

const messages = pluginMessages.excelInput;

const excelInputSchema: FlatFormSchema = {
  fields: [
    {
      key: "sourceType",
      label: messages.sourceTypeLabel,
      dataType: "STRING",
      renderType: "DROPDOWN",
      required: true,
      defaultValue: "LOCAL",
      options: [
        { label: messages.sourceTypeLocal, value: "LOCAL" },
        { label: messages.sourceTypeSftp, value: "SFTP" },
      ],
    },
    {
      key: "fileName",
      label: messages.localUploadLabel,
      dataType: "STRING",
      renderType: "FILE_UPLOAD",
      required: true,
      defaultValue: "",
      accept: ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      visibleWhenKey: "sourceType",
      visibleWhenValue: "LOCAL",
    },
    {
      key: "fileName",
      label: messages.fileNameLabel,
      dataType: "STRING",
      renderType: "INPUT",
      required: true,
      defaultValue: "",
      placeholder: messages.fileNamePlaceholder,
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
    {
      key: "sheetName",
      label: messages.sheetNameLabel,
      dataType: "STRING",
      renderType: "INPUT",
      required: false,
      defaultValue: "",
      placeholder: messages.sheetNamePlaceholder,
    },
    {
      key: "sftpHost",
      label: messages.sftpHostLabel,
      dataType: "STRING",
      renderType: "INPUT",
      required: true,
      defaultValue: "",
      placeholder: "localhost",
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
    {
      key: "sftpPort",
      label: messages.sftpPortLabel,
      dataType: "NUMBER",
      renderType: "INPUT",
      required: true,
      defaultValue: 22,
      min: 1,
      max: 65535,
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
    {
      key: "sftpUsername",
      label: messages.sftpUsernameLabel,
      dataType: "STRING",
      renderType: "INPUT",
      required: true,
      defaultValue: "",
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
    {
      key: "sftpPassword",
      label: messages.sftpPasswordLabel,
      dataType: "STRING",
      renderType: "PASSWORD",
      required: false,
      defaultValue: "",
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
    {
      key: "sftpBaseDirectory",
      label: messages.sftpBaseDirectoryLabel,
      dataType: "STRING",
      renderType: "INPUT",
      required: true,
      defaultValue: "",
      placeholder: "/upload",
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
    {
      key: "sftpHostKeySha256",
      label: messages.sftpHostKeyLabel,
      dataType: "STRING",
      renderType: "INPUT",
      required: true,
      defaultValue: "",
      placeholder: "SHA256:...",
      visibleWhenKey: "sourceType",
      visibleWhenValue: "SFTP",
    },
  ],
};

export const excelInputConfigurationDefinition = createFormPluginDefinition({
  pluginType: "core.excel-input",
  schema: excelInputSchema,
});
